spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
     server:
        git:
          uri: https://github.com/rushikeshnkulkarni/configserver
          clone-on-start: true

         # try-master-branch: false

server:
  port: 8087

eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8084/eureka/

